services:
  postgres:
    image: postgres:15
    container_name: transporte-db
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - transporte-data:/var/lib/postgresql/data
    networks:
      - transporte-net

  backend:
    build: ./back
    container_name: transporte-back
    env_file: .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - transporte-net

  frontend:
    build: ./front
    container_name: transporte-front
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - transporte-net

networks:
  transporte-net:
    driver: bridge

volumes:
  transporte-data: